### ISSUE TITLE
TODO!

### ISSUE THREAD

**Issue by PetrushynskyiOleksii** [PetrushynskyiOleksii/jammed#30]
- [x] Remove height in `nav-btn` css
- [x] Set y-axis to display data in the middle of graph
- [x] Set default delta to 10800
- [x] Change trip id to license plate
- [x] Implement scatter chart
- [x] Set x-axis, y-axis ticks for scatter plot
- [x] No data points error
- [x] Fix xaxis ticks
- [x]  Scatter plot timestamp
- [x]  Auto update transport page
- [x] Invalid active button after reload
- [x]  Search button for openning dialog window
- [x]  Last Value at center
- [x]  Implement fixed loop icon
- [x]  Format timestamps move to utils
- [x] Set ErrorIcon for errors (import ErrorIcon from '@material-ui/icons/Error';)
- [x] Set WarningIcon for `No data points` (import WarningIcon from '@material-ui/icons/Warning';)
- [x] Implement pop up window
- [x]  Implement query for transports
- [x]  Implement search item buttons for transports
- [x]  Implement chart message if route name choosen
- [x]  Change background color
- [x]  Set always visible last value on charts
- [x]  Set routeName to local storage
- [x]  Format ticks on scatter tile
- [x]  Create route model
- [x]  Implement aggrate method in monger
- [x]  Return only cursor from each monger methods
- [x]  Handle stop iteration in timeserise/coordinates endpoint
- [x]  Move cursor to models
- [x]  Parse transport type from short name
- [x]  Remove useless code from mongo worker
- [x]  Add route name to transport charts
- [x]  Check if pid exists during starting collector
- [x]  Retry creating mongo worker
- [x]  Fix title margin
- [x] implement right/left click on line graphs
- [x] Implement count documents
- [x] Get region by geopy
- [x] Downloading files
- [x] Fix active button if use localhost:3000
- [x] Fix double rendering
- [x] Fix transport per routes
